### PR TITLE
8288101: False build warning-as-error with GCC 9 after JDK-8214976

### PR DESCRIPTION
**Pull request by shipilev**
gcc version 9.4.0 (also 9.3.1) produces build warning after [JDK-8214976](https://bugs.openjdk.org/browse/JDK-8214976):

```
os_posix.cpp:786:34: error: call to 'exit' declared with attribute warning: use os::exit [-Werror=attribute-warning]
  786 | ALLOW_C_FUNCTION(::exit, ::exit(num);)
      | ~~~~~~^~~~~
```

Apparently, GCC 9 has a bug with nesting pragmas. The [Godbolt experiments](https://godbolt.org/z/vonsqEnK6) show this only affects GCC 9, and there are no easy way to restructure the macros to dodge this, so the way out to bump the requirement for new macros to GCC >= 10.

Additional testing:
 - [x] Linux x86_64 build with GCC 9.4.0 (now passes without warnings)
 - [x] Linux x86_64 build with GCC 10.2.1 (still passes)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288101](https://bugs.openjdk.org/browse/JDK-8288101): False build warning-as-error with GCC 9 after JDK-8214976

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19 pull/1/head:pull/1` \
`$ git checkout pull/1`

Update a local copy of the PR: \
`$ git checkout pull/1` \
`$ git pull https://git.openjdk.org/jdk19 pull/1/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1`

View PR using the GUI difftool: \
`$ git pr show -t 1`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19/pull/1.diff">https://git.openjdk.org/jdk19/pull/1.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Thanks for fixing it! LGTM.

**Review by kimbarrett — APPROVED** [review]
Looks good.
